spring:
  application:
    name: spring-security-demo-1
  datasource:
    password: postgrespw
    url: jdbc:postgresql://localhost:55000/spring-security-demo-1
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        provider:
          keycloak:            
            issuer-uri: http://localhost:8180/auth/realms/SpringBootKeycloak
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: spring-app
            authorization-grant-type: authorization_code
            scope: openid

server:
  port: 9080
